### ISSUE TITLE
NVME Support

### ISSUE THREAD

**Issue by anhnvme** [dandantsui/Lenovo-M900-Tiny-Hackintosh#1]
Hello,

Dose this EFI support NVME PCI SSD ?

Thanks

**Comment by dandantsui** [comment]
No it doesn’t. I’m unable to verify if it works either but you can add the corresponding .efi files to clover and you should be able to use it.

**Comment by anhnvme** [comment]
Thanks for your reply

Current, i'm work perfect with SATA SSD but, while install NVME SSD, it's show NVME as external Disk.
I can install, but when i mout EFI Partision, it's show not thing, i'm tried copy EFI from SATA to NVME EFI but can't not boot

If u know, please tell me

thanks again

**Comment by dandantsui** [comment]
Hi, you want to run Clover installation again and install NvmeExpressDxe. That should fix it.

https://user-images.githubusercontent.com/62964600/87213849-df1c7800-c2dc-11ea-84c8-6f6b7ac23846.png

**Comment by anhnvme** [comment]
WOW, ok, i will try and let's u know. Thanks so much

**Comment by anhnvme** [comment]
Hello,

that drivers not work. My friend share me a this kext ( https://github.com/acidanthera/NVMeFix/  ).
It's work correctly now

Thanks for your support

**Comment by dandantsui** [comment]
Did you keep the NVME DXE in? I believe that you wouldn't have been able to boot without it. NVMeFix only applies to a subset of NVMe drives, but you didn't list which drive you had.

**Comment by anhnvme** [comment]
> Did you keep the NVME DXE in? I believe that you wouldn't have been able to boot without it. NVMeFix only applies to a subset of NVMe drives, but you didn't list which drive you had.

No, after your reply, i just know nvmedxe driver. while my friend put kext with orginal EFI before put nvmedxe drivers, my nvme booted
